### ISSUE TITLE
Artikli sisust piltide mappimine

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web#212]
Artikli contents objekti sees on pildid, mille URL on Strapi media library URL. Neid ei ole õigus nähe neil, kellel pole strapi ligipääsu e kõigile peale toimetajate. 
Oleks vaja fetch nii ümber teha, et pildid asuksid Zones koos teiste piltidega, mitte Strapis.

**Comment by mpennaste** [comment]
@jaanleppik 
Tehtud pull requesti masterisse "Article content img fetch" harust, vaata üle ja kui korras, merge ära.
Artikli download img script tõmbab nüüd pildid artiklite sisust assets folderisse ja sisus artiklite fetch script strapi lingid vahetab kohaliku assets folder vastu.
Töötab hetkel vaid piltidega mis lisatud strapist artikli sisusse eeldusel, et toimetajad nii toimetavadki.

**Comment by mitselek** [comment]
Vau. Kiire t88. Homme vaatan yle
