### ISSUE TITLE
Refactor frontend. Use film.orderedCountries instead of film.countries

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web#402]
https://github.com/poff-bnff/web/blob/d636eee0821ae711c079bcad6e931ef4d69cb0a1/eventival/scripts/toStrapi.js#L383-L383

**Comment by mitselek** [comment]
strapisse on komponendina imporditud, strapidatasse tuleb ka.
paralleelsena on esialgu veel alles ka film.countries

- [ ] võtta layoutil kasutusele film.orderedCounttries
- [ ] lõpetada strapisse film.countries importimine
- [ ] kustutada strapist ja andmemudelist film.countries

**Comment by mpennaste** [comment]
Kasseti all nüüd film.orderedCountries
