### ISSUE TITLE
peale kasutajaks registreerumist brauseris konsoolil vead

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web#497]
![Screenshot 2020-11-06 at 21 05 00](https://user-images.githubusercontent.com/873710/98404796-e62d7a00-2073-11eb-8829-dcf41b6bd8de.png)
![Screenshot 2020-11-06 at 21 05 29](https://user-images.githubusercontent.com/873710/98404805-e9c10100-2073-11eb-973a-c8ab48cfe5c9.png)

**Comment by SiimS1** [comment]
Fixed:

added element 'loginButton' to signUp page, which opens loginpage according to locale
