### ISSUE TITLE
https://dev.inscaping.eu/minupoff/

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web#500]
![Screenshot 2020-11-06 at 21 26 25](https://user-images.githubusercontent.com/873710/98406526-cfd4ed80-2076-11eb-8b60-3efdb12cf924.png)
![Screenshot 2020-11-06 at 21 28 08](https://user-images.githubusercontent.com/873710/98406619-f98e1480-2076-11eb-8041-913a2054f547.png)
![Screenshot 2020-11-06 at 21 28 33](https://user-images.githubusercontent.com/873710/98406649-07439a00-2077-11eb-9516-d2d16a67f790.png)

**Comment by SiimS1** [comment]
Fixed:

short: Access-Control-Allow-Origin - restarted allow all origins

long:
AWS Api Gateway-Develop-Cors-Configure
removed *
tested fb login not working cause CORS
added * again
tested fb login - working cause *-allowed from all origins
passes now showing on mypoff page
